Bugfix associativity
matthew-mccall/Oasis pull request #46
Opened 2023-12-08 17:08 UTC by 404Naz

Added associativity to addition and multiplication.

2023-12-08 17:18 UTC, 404Naz commented
Divide relies on unsimplified trees to simplify the problem. Some tests cause problems since add and multiply will attempt to make balanced trees. Thus, I commented out the problematic test cases.

2023-12-08 17:49 UTC, matthew-mccall requested changes
Make the commented out test cases work

2024-02-06 22:35 UTC, matthew-mccall requested changes

2024-02-06 22:35 UTC, matthew-mccall commented on src/Divide.cpp
> -    // log(a) / log(b) = log[b](a)
Put the comment back

2024-02-06 22:35 UTC, matthew-mccall commented on src/Divide.cpp
> +    /*
Remove if commented out

2024-02-06 22:35 UTC, matthew-mccall commented on tests/DivideTests.cpp
> +    // somehow equals is broken? Not really sure
?

2024-02-09 22:13 UTC, matthew-mccall approved these changes

2024-02-10 18:20 UTC, merged