Exponent
matthew-mccall/Oasis pull request #8
Opened 2023-09-29 21:16 UTC by 404Naz

Completed exponent for variable base and real power and real base and real power.

2023-09-30 19:07 UTC, matthew-mccall requested changes
We have to work on replacing the specific cases for `Variable` with cases that work on any general `Expression`

2023-09-30 19:07 UTC, matthew-mccall commented on include/Oasis/Exponent.hpp
Make sure to add Doxygen comments: https://www.doxygen.nl/manual/docblocks.html

2023-09-30 20:54 UTC, Jdpankow approved these changes

2023-10-06 20:32 UTC, matthew-mccall requested changes
In `Add` and `Subtract` you still need to update the code to handle and `Expression` instead of just `Variable`s

2023-10-06 20:32 UTC, matthew-mccall commented on src/Add.cpp
You need to make for this work for any `Expression` not just `Variable`

2023-10-06 20:32 UTC, matthew-mccall commented on src/Subtract.cpp
You also should update this

2023-10-06 23:51 UTC, 404Naz commented
Updated Add.cpp and Subtract.cpp

2023-10-07 02:56 UTC, matthew-mccall approved these changes

2023-10-07 03:22 UTC, merged