Feature integration
matthew-mccall/Oasis pull request #80
Opened 2024-03-26 21:04 UTC by Eagle1456

Add integration functionality for the following rules:
- Constant rule
- Single variable same rule
- Multiplication by constant rule
- Power rule
- Sum rule
- Difference rule

2024-04-05 02:08 UTC, matthew-mccall requested changes
Looks good for a start. A couple things to change:
1. Use the declarative syntax and then call `Simplify` on the temporary. This should make the code more readable than use `std::make_unique`
2. In some cases you return a `Copy()` of the Expression when mathematically speaking it should be in the integrand of an integral. So we need to add an `Integral` binary node.
3. You have a lot of code nested in conditionals that check if the integrating variable is a variable. Consider using early returns instead of nesting code.

I understand these may not have been clarified before, so I will be sure to add them the guidelines now.

2024-04-05 02:08 UTC, matthew-mccall commented on src/Multiply.cpp
> +            auto integrated = (*exp).Integrate(integrationVariable);
Why not use the arrow syntax?

2024-04-22 17:41 UTC, Eagle1456 commented
@matthew-mccall, to address the changes requested:

1. Resolved
2. Resolved with assistance of @LevyLCH 
3. The only thing is that some of the classes use the Variable.GetName() function which can only be discerned if the Variable class is specialized.

2024-04-26 20:52 UTC, matthew-mccall requested changes

2024-04-26 20:52 UTC, matthew-mccall commented on include/Oasis/Integrate.hpp
Rename the class to `Integral`

2024-04-26 20:52 UTC, matthew-mccall commented on include/Oasis/Expression.hpp
Rename the function to `Integrate` to be consistent

2024-04-26 20:52 UTC, matthew-mccall commented on src/Integrate.cpp
The `Integration` logic should be inside the `Add`, `Exponent`, etc. classes. The `Integral` class is meant to be a wrapper such that calling `Simplify` on an integral is what performs the integration by calling `Integrate` on the operands.

2024-04-30 14:32 UTC, matthew-mccall requested changes

2024-04-30 14:32 UTC, matthew-mccall commented on include/Oasis/Expression.hpp
> +    [[nodiscard]] virtual auto Integrate(const Expression&, const Expression&, const Expression&) -> std::unique_ptr<Expression>;
Rename this to IntegrateWithBounds as to portray clearer intent

2024-04-30 14:38 UTC, matthew-mccall commented
@Eagle1456  Hi, thank you for picking up on the changes with regards to refactoring out the `ToString` and `MathML` functions. I will be required `Oasis::Extras` to be able to build successfully soon, so please look out for when that gets merged in, and make sure to implement the necessary serialization functions. (I see you declared them, but not defined them). Also rename the definite `Integrate` function to `IntegrateWithBounds`. Other than that, looks good to me. I will merge once those changes are made.

2024-05-13 21:28 UTC, matthew-mccall approved these changes

2024-05-13 21:29 UTC, merged